using Backlog.Modules.Inbox.Abstractions;
using Backlog.Modules.Inbox.Abstractions.DataTransferObjects;
using Backlog.Modules.Inbox.Abstractions.Services;
using Backlog.Modules.Inbox.DomainModels;
using Backlog.Modules.Inbox.Features.DismissSuggestion;
using Backlog.Modules.Inbox.Features.Suggest;
using Backlog.Modules.Inbox.Services;

namespace Backlog.Modules.Inbox.UnitTests;

/// <summary>
/// Classification's suggestions: which tags, repositories and destination an
/// open item is offered, and the one rule the reader leans on — a suggestion
/// turned down is recorded on the item and never offered for it again.
/// </summary>
public sealed class SuggestionTests
{
    private static readonly DateTimeOffset Noon = Items.Noon;

    private static InboxItem Item(
        string title,
        string body = "",
        ContentKind kind = ContentKind.Text,
        string channel = InboxEnumMap.ManualChannel,
        string? person = null,
        string? sourceUrl = null) =>
        new(Guid.CreateVersion7(), title, body, sourceUrl, Noon, Noon, kind, new InboxSource(channel, person), replicaBacked: false);

    private static IReadOnlyList<InboxSuggestionDto> Suggest(
        InboxItem item,
        IReadOnlyList<string>? backlogTags = null,
        IReadOnlyList<InboxRoutingRule>? rules = null) =>
        InboxClassifier.Suggest(item, backlogTags ?? [], rules ?? []);

    private static IReadOnlyList<string> Values(IEnumerable<InboxSuggestionDto> suggestions, InboxSuggestionKind kind) =>
        [.. suggestions.Where(suggestion => suggestion.Kind == kind).Select(suggestion => suggestion.Value)];

    // --- Tags ----------------------------------------------------------------

    [Fact]
    public void A_hashtag_in_the_body_is_offered_as_a_tag()
    {
        var item = Item("Look at the sync bug", "Seen again today #sync #flaky-tests");

        Assert.Equal(["sync", "flaky-tests"], Values(Suggest(item), InboxSuggestionKind.Tag));
    }

    [Theory]
    [InlineData("Read https://example.com/page#section today")]
    [InlineData("See the heading\n## Setup")]
    [InlineData("Fixes #123")]
    [InlineData("A link to /#top")]
    public void An_anchor_a_heading_or_an_issue_number_is_not_a_hashtag(string body)
    {
        Assert.Empty(Values(Suggest(Item("Note", body)), InboxSuggestionKind.Tag));
    }

    [Fact]
    public void A_backlog_tag_the_text_mentions_as_a_word_is_offered_in_the_backlogs_spelling()
    {
        var item = Item("The Sync service drops release notes", "and the ui flickers");

        var tags = Values(Suggest(item, backlogTags: ["sync", "release-notes", "UI", "docs"]), InboxSuggestionKind.Tag);

        Assert.Equal(["sync", "release-notes", "UI"], tags);
    }

    [Fact]
    public void A_backlog_tag_inside_a_longer_word_is_not_offered()
    {
        var item = Item("Asynchronous uploads");

        Assert.Empty(Values(Suggest(item, backlogTags: ["sync"]), InboxSuggestionKind.Tag));
    }

    [Fact]
    public void A_hashtag_the_backlog_already_has_takes_the_backlogs_spelling_and_is_offered_once()
    {
        var item = Item("Deploy notes #deploy", "the deploy failed");

        var tags = Suggest(item, backlogTags: ["Deploy"]).Where(suggestion => suggestion.Kind == InboxSuggestionKind.Tag).ToList();

        var only = Assert.Single(tags);
        Assert.Equal("Deploy", only.Value);
        Assert.Equal("tag:deploy", only.Key);
    }

    [Fact]
    public void A_tag_the_item_already_carries_is_not_offered()
    {
        var item = Item("About #sync");
        item.SetTags([new InboxTag("Sync", AutoGenerated: false)]);

        Assert.Empty(Values(Suggest(item, backlogTags: ["sync"]), InboxSuggestionKind.Tag));
    }

    [Fact]
    public void At_most_five_tags_are_offered()
    {
        var item = Item("Many", "#a1 #b2 #c3 #d4 #e5 #f6 #g7");

        Assert.Equal(InboxClassifier.MaxTagSuggestions, Values(Suggest(item), InboxSuggestionKind.Tag).Count);
    }

    // --- Repositories ------------------------------------------------------------

    [Fact]
    public void A_tag_rule_offers_its_repository_for_an_item_carrying_a_matching_tag()
    {
        var item = Item("Colours");
        item.SetTags([new InboxTag("design-tokens", AutoGenerated: false)]);
        InboxRoutingRule[] rules = [new("#design*", "JSdotNet/Design"), new("#sync", "JSdotNet/Sync")];

        var suggestion = Assert.Single(Suggest(item, rules: rules), s => s.Kind == InboxSuggestionKind.Repository);

        Assert.Equal("JSdotNet/Design", suggestion.Value);
        Assert.Equal("repository:jsdotnet/design", suggestion.Key);
        Assert.Contains("#design* => JSdotNet/Design", suggestion.Reason, StringComparison.Ordinal);
    }

    [Fact]
    public void A_tag_rule_reads_the_tags_the_item_carries_not_the_ones_only_suggested()
    {
        var item = Item("About #design");

        Assert.Empty(Values(Suggest(item, rules: [new("#design", "JSdotNet/Design")]), InboxSuggestionKind.Repository));
    }

    [Fact]
    public void A_person_rule_matches_who_shared_the_item()
    {
        var item = Item("Have a look", channel: "mobile", person: "@alice");

        var repos = Values(Suggest(item, rules: [new("@alice", "JSdotNet/Alice"), new("@bob", "JSdotNet/Bob")]), InboxSuggestionKind.Repository);

        Assert.Equal(["JSdotNet/Alice"], repos);
    }

    [Fact]
    public void A_source_rule_matches_the_channel_or_the_link()
    {
        var video = Item("Talk", kind: ContentKind.YouTube, channel: "youtube");
        var issue = Item("Bug", sourceUrl: "https://github.com/JSdotNet/Backlog/issues/9");
        InboxRoutingRule[] rules = [new("youtube", "JSdotNet/Watch"), new("*github.com/JSdotNet/*", "JSdotNet/Backlog")];

        Assert.Equal(["JSdotNet/Watch"], Values(Suggest(video, rules: rules), InboxSuggestionKind.Repository));
        Assert.Equal(["JSdotNet/Backlog"], Values(Suggest(issue, rules: rules), InboxSuggestionKind.Repository));
    }

    [Fact]
    public void A_repository_already_assigned_is_not_offered_and_two_rules_for_one_repository_offer_it_once()
    {
        var item = Item("Bug", channel: "mobile", person: "@alice");
        item.SetRepoIds(["JSdotNet/Backlog"]);
        InboxRoutingRule[] rules = [new("mobile", "JSdotNet/Backlog"), new("mobile", "JSdotNet/Phone"), new("@alice", "JSdotNet/Phone")];

        Assert.Equal(["JSdotNet/Phone"], Values(Suggest(item, rules: rules), InboxSuggestionKind.Repository));
    }

    // --- Destination ---------------------------------------------------------------

    [Fact]
    public void A_note_of_the_readers_own_is_offered_the_backlog()
    {
        var destination = Assert.Single(Suggest(Item("Call the dentist")), s => s.Kind == InboxSuggestionKind.Destination);

        Assert.Equal("tasks", destination.Value);
        Assert.Equal("destination:tasks", destination.Key);
        Assert.True(destination.Available);
    }

    [Fact]
    public void An_item_with_a_repository_is_offered_the_backlog_whatever_its_kind()
    {
        var item = Item("Local-first patterns", kind: ContentKind.Article);
        item.SetRepoIds(["JSdotNet/Backlog"]);

        Assert.Equal(["tasks"], Values(Suggest(item), InboxSuggestionKind.Destination));
    }

    [Fact]
    public void Collected_material_is_offered_knowledge_which_cannot_be_taken_yet()
    {
        var destination = Assert.Single(
            Suggest(Item("Local-first patterns", kind: ContentKind.Article)),
            s => s.Kind == InboxSuggestionKind.Destination);

        Assert.Equal("devbook", destination.Value);
        Assert.False(destination.Available);
        Assert.Equal(InboxClassifier.KnowledgeNotBuilt, destination.UnavailableReason);
    }

    [Fact]
    public void A_newsletter_is_offered_archive()
    {
        var item = Item("Weekly digest", "Ten links this week. Unsubscribe here.", kind: ContentKind.Email, channel: "email");

        Assert.Equal(["archive"], Values(Suggest(item), InboxSuggestionKind.Destination));
    }

    // --- Nothing applied, nothing for a decided item ---------------------------------

    [Fact]
    public void Suggesting_changes_nothing_about_the_item()
    {
        var item = Item("About #sync");
        var stamp = item.UpdatedAt;

        _ = Suggest(item, backlogTags: ["sync"], rules: [new("manual", "JSdotNet/Backlog")]);

        Assert.Empty(item.Tags);
        Assert.Empty(item.RepoIds);
        Assert.Equal(InboxStatus.Unprocessed, item.Status);
        Assert.Equal(stamp, item.UpdatedAt);
    }

    [Fact]
    public void A_routed_or_archived_item_is_offered_nothing()
    {
        var routed = Item("Routed #sync");
        routed.RouteToBacklog([Guid.CreateVersion7()], [], Noon);
        var archived = Item("Archived #sync");
        archived.Archive(Noon);

        Assert.Empty(Suggest(routed, backlogTags: ["sync"]));
        Assert.Empty(Suggest(archived, backlogTags: ["sync"]));
    }

    [Fact]
    public void A_deferred_item_is_still_offered_suggestions()
    {
        var item = Item("Later #sync");
        item.Defer(until: null, Noon);

        Assert.Contains(Suggest(item), s => s.Key == "tag:sync");
    }

    // --- Turned down stays turned down ----------------------------------------------

    [Fact]
    public void A_dismissed_suggestion_is_not_offered_again_whatever_proposes_it()
    {
        var item = Item("About #sync");
        item.SetTags([new InboxTag("design", AutoGenerated: false)]);
        item.DismissSuggestion("tag:sync");
        item.DismissSuggestion("repository:JSdotNet/Design");
        item.DismissSuggestion("destination:tasks");

        // #sync is now both written in the text and a backlog tag; still refused.
        var suggestions = Suggest(item, backlogTags: ["sync"], rules: [new("#design", "JSdotNet/Design")]);

        Assert.Empty(suggestions);
    }

    [Fact]
    public void A_dismissed_destination_is_not_replaced_by_another_guess()
    {
        var item = Item("Weekly digest", "Unsubscribe here.");
        item.DismissSuggestion("destination:archive");

        Assert.Empty(Values(Suggest(item), InboxSuggestionKind.Destination));
    }

    [Fact]
    public async Task The_query_reads_the_backlogs_tags_and_the_rules_and_the_command_records_a_refusal()
    {
        var store = new InMemoryInboxStore();
        var item = Item("The sync service", channel: "mobile");
        store.Seed(item);
        var query = new SuggestQueryHandler(store, new StubTags("sync"), new StubRules(new InboxRoutingRule("mobile", "JSdotNet/Phone")));
        var ct = TestContext.Current.CancellationToken;

        var first = await query.Handle(new SuggestQuery(item.Id), ct);

        Assert.True(first.IsSuccess);
        Assert.Equal(["tag:sync", "repository:jsdotnet/phone", "destination:tasks"], first.Value.Select(s => s.Key));
        Assert.Empty(store.ItemWrites);

        var dismissed = await new DismissSuggestionCommandHandler(store).Handle(new DismissSuggestionCommand(item.Id, "tag:sync"), ct);
        var second = await query.Handle(new SuggestQuery(item.Id), ct);

        Assert.True(dismissed.IsSuccess);
        Assert.Equal([item.Id], store.ItemWrites);
        Assert.Equal(["repository:jsdotnet/phone", "destination:tasks"], second.Value.Select(s => s.Key));
    }

    [Fact]
    public async Task Dismissing_twice_writes_once_and_a_blank_key_or_a_missing_item_is_refused()
    {
        var store = new InMemoryInboxStore();
        var item = Item("Note");
        store.Seed(item);
        var handler = new DismissSuggestionCommandHandler(store);
        var ct = TestContext.Current.CancellationToken;

        await handler.Handle(new DismissSuggestionCommand(item.Id, "tag:sync"), ct);
        var again = await handler.Handle(new DismissSuggestionCommand(item.Id, "TAG:Sync "), ct);
        var blank = await handler.Handle(new DismissSuggestionCommand(item.Id, " "), ct);
        var missing = await handler.Handle(new DismissSuggestionCommand(Guid.CreateVersion7(), "tag:sync"), ct);

        Assert.True(again.IsSuccess);
        Assert.Single(store.ItemWrites);
        Assert.Equal(["tag:sync"], item.DismissedSuggestions);
        Assert.Equal(InboxErrors.SuggestionKeyRequired, blank.Error);
        Assert.Equal(InboxErrors.ItemNotFound, missing.Error);
    }

    [Fact]
    public async Task Without_a_tag_source_or_rules_the_query_still_answers_what_the_text_supports()
    {
        var store = new InMemoryInboxStore();
        var item = Item("About #sync");
        store.Seed(item);

        var answer = await new SuggestQueryHandler(store).Handle(new SuggestQuery(item.Id), TestContext.Current.CancellationToken);

        Assert.Equal(["tag:sync", "destination:tasks"], answer.Value.Select(s => s.Key));
    }

    /// <summary>The list's markers ask for every row at once: each item gets
    /// what it would be offered alone, an id with no item is left out, and the
    /// backlog's tags are read once for the lot rather than once per row.</summary>
    [Fact]
    public async Task The_batch_query_answers_each_item_and_reads_the_tags_once()
    {
        var store = new InMemoryInboxStore();
        var sync = Item("The sync service");
        var note = Item("A note of my own");
        store.Seed(sync);
        store.Seed(note);
        var tags = new StubTags("sync");
        var query = new SuggestQueryHandler(store, tags);
        var missing = Guid.CreateVersion7();

        var answer = await query.Handle(new SuggestManyQuery([sync.Id, note.Id, missing]), TestContext.Current.CancellationToken);

        Assert.True(answer.IsSuccess);
        Assert.Equal(new[] { sync.Id, note.Id }.Order(), answer.Value.Keys.Order());
        Assert.Contains("tag:sync", answer.Value[sync.Id].Select(s => s.Key));
        Assert.DoesNotContain("tag:sync", answer.Value[note.Id].Select(s => s.Key));
        Assert.Equal(1, tags.Reads);
    }

    private sealed class StubTags(params string[] tags) : IBacklogTagSource
    {
        public int Reads { get; private set; }

        public Task<IReadOnlyList<string>> TagsInUseAsync(CancellationToken cancellationToken = default)
        {
            Reads++;
            return Task.FromResult<IReadOnlyList<string>>(tags);
        }
    }

    private sealed class StubRules(params InboxRoutingRule[] rules) : IInboxRoutingRules
    {
        public event Action? Changed
        {
            add { }
            remove { }
        }

        public IReadOnlyList<InboxRoutingRule> Current => rules;

        public string? SetRules(string? text) => null;
    }
}
