using System.Text.Json;
using System.Text.RegularExpressions;

namespace Backlog.ArchitectureTests;

/// <summary>
/// Rules for the motion in the committed Archify artifacts.
///
/// <para>An Archify artifact animates only if its specification asked it to.
/// <c>meta.animation</c> is an <c>enum ["trace", "none"]</c> in all five of
/// Archify's schemas and its default is static, so a specification that says
/// nothing renders a diagram that never moves. That default is the opposite of
/// what this repository wants — the knowledge pane shows these artifacts because
/// a traced edge is how a reader follows a flow — and nothing else notices the
/// difference: a static artifact is a valid, complete, nine-of-nine-checks
/// artifact. It renders, it exports, it passes every gate Archify has. It just
/// sits there.</para>
///
/// <para>All forty-two artifacts shipped that way, and the miss survived a first
/// investigation because the evidence reads backwards. Every artifact embeds the
/// stylesheet that would drive the motion, so <c>grep data-animation="trace"</c>
/// finds fifteen hits per file and <c>grep data-animate</c> finds dozens — all of
/// them selectors in that stylesheet, none of them on an element. The two rules
/// below therefore match where the attributes would actually have to be: on the
/// diagram's own <c>&lt;svg&gt;</c> tag, and on elements paired with the
/// <c>--step</c> custom property the keyframes read.</para>
///
/// <para>Both halves are checked because both can be lost on their own. A
/// specification edited without a re-render leaves the artifact static while the
/// specification claims otherwise; a re-render from an Archify upgrade that
/// changed the contract leaves the artifact carrying one half and not the
/// other.</para>
/// </summary>
public class ArchifyArtifactMotionTests
{
    /// <summary>The knowledge folders that hold chapter artifacts, mirroring
    /// <c>KNOWLEDGE_FOLDERS</c> in <c>tools/diagrams/archify-artifacts.mjs</c>.
    /// <c>.design</c> has no artifacts today and is listed anyway, so the first
    /// one authored there is covered without anybody remembering this file.</summary>
    private static readonly string[] KnowledgeFolders = [".arc42", ".domain", ".tech", ".design"];

    /// <summary>The artifact folder beside a chapter.</summary>
    private const string ArtifactFolder = "_archify";

    /// <summary>The storybook's three samples, which are authored the same way and
    /// regenerated by the same procedure but sit outside the knowledge folders.</summary>
    private static readonly string[] StorybookFolder =
        ["src", "Harness", "Backlog.UI.Storybook", "wwwroot", "archify"];

    /// <summary>What a specification has to ask for.</summary>
    private const string Trace = "trace";

    /// <summary>
    /// The diagram's own <c>&lt;svg&gt;</c> tag, picked out by the accessible name
    /// Archify gives the one primary diagram in an artifact. Matching the tag
    /// rather than the file is the whole point: the stylesheet inside every
    /// artifact is full of <c>svg[data-animation="trace"]</c> selectors that a
    /// whole-file search cannot tell from the real thing.
    /// </summary>
    private static readonly Regex DiagramSvgTag =
        new("<svg\\b[^>]*aria-labelledby=\"archify-diagram-title[^>]*>", RegexOptions.Compiled);

    /// <summary>
    /// An element Archify marked for animation. The <c>--step</c> custom property
    /// is required rather than incidental: it is what staggers the trace, the
    /// keyframes read it through <c>animation-delay</c>, and it is emitted by the
    /// same branch as the attribute, so an element carrying one and not the other
    /// means the renderer's contract moved.
    /// </summary>
    private static readonly Regex AnimatedElement =
        new("data-animate=\"(?:edge|node)\" style=\"--step:\\d+\"", RegexOptions.Compiled);

    [Fact]
    public void Every_archify_specification_asks_for_the_trace_animation()
    {
        var specifications = Specifications().ToList();

        Assert.True(
            specifications.Count > 0,
            "This rule found no Archify specifications at all, so it is passing on nothing. Either the "
            + "artifacts moved out of _archify/ and the storybook folder, or the paths here are stale.");

        foreach (var specification in specifications)
        {
            using var document = JsonDocument.Parse(File.ReadAllText(specification.FullName));

            var animation = document.RootElement.TryGetProperty("meta", out var meta)
                            && meta.TryGetProperty("animation", out var value)
                ? value.GetString()
                : null;

            Assert.True(
                animation == Trace,
                $"{Relative(specification)} sets meta.animation to {Describe(animation)}, not \"{Trace}\". "
                + "Archify's default is static, so this diagram renders as a picture that never moves. "
                + "The reader gets no traced edge, and nothing else reports it — the artifact still passes "
                + "all nine of Archify's checks.");
        }
    }

    [Fact]
    public void Every_archify_artifact_carries_the_motion_its_specification_asked_for()
    {
        var artifacts = Artifacts().ToList();

        Assert.True(
            artifacts.Count > 0,
            "This rule found no Archify artifacts at all, so it is passing on nothing. Either the "
            + "artifacts moved out of _archify/ and the storybook folder, or the paths here are stale.");

        foreach (var artifact in artifacts)
        {
            var html = File.ReadAllText(artifact.FullName);
            var tag = DiagramSvgTag.Match(html);

            Assert.True(
                tag.Success,
                $"{Relative(artifact)} has no diagram <svg> carrying the archify-diagram-title accessible "
                + "name, so this rule cannot see what it is meant to check. If Archify changed how it "
                + "names the primary diagram, teach this rule the new shape rather than letting it pass "
                + "on a file it did not read.");

            Assert.True(
                tag.Value.Contains($"data-animation=\"{Trace}\"", StringComparison.Ordinal),
                $"{Relative(artifact)} draws its diagram without data-animation=\"{Trace}\" on the <svg>. "
                + "Archify's Motion Governor reads exactly that attribute to decide whether the document "
                + "is motion-capable; without it the artifact never sets data-ambient-motion=\"running\" "
                + "and every animation rule in its own stylesheet stays inert. Regenerate this artifact "
                + "from its specification.");

            Assert.True(
                AnimatedElement.IsMatch(html),
                $"{Relative(artifact)} marks no element with data-animate and a --step, so there is "
                + "nothing for the trace to run on even once the switch is set. The renderer emits the "
                + "switch and these hooks from the same flag, so an artifact with one and not the other "
                + "was not regenerated as a whole — re-render it rather than patching the HTML.");
        }
    }

    /// <summary>
    /// The vendored Archify CLI is committed.
    ///
    /// <para>It was not, for the whole life of the feature. <c>.gitignore</c>
    /// carries <c>[Bb]in/</c> for .NET build output, that rule matched
    /// <c>tools/archify/bin/</c>, and the four entrypoints went with it —
    /// including the <c>archify.mjs</c> that <c>tools/diagrams/archify-artifacts.mjs</c>
    /// spawns. Every regeneration therefore failed with MODULE_NOT_FOUND on a
    /// fresh clone, which is precisely when somebody would be trying to fix an
    /// artifact.</para>
    ///
    /// <para>Nothing caught it because the two commands anyone runs to check the
    /// artifacts — <c>scan</c> and <c>verify</c> — read the index and the chapters
    /// and never shell out. Both report green against a generator that cannot
    /// generate.</para>
    /// </summary>
    [Fact]
    public void The_vendored_archify_cli_is_committed()
    {
        var cli = Path.Combine(RepositoryRoot.Root.FullName, "tools", "archify", "bin", "archify.mjs");

        Assert.True(
            File.Exists(cli),
            "tools/archify/bin/archify.mjs is missing. tools/diagrams/archify-artifacts.mjs spawns it to "
            + "render every artifact, and tools/archify/UPSTREAM.md promises it works offline on a fresh "
            + "clone. .gitignore's [Bb]in/ rule is what removes it, so restoring the file also needs the "
            + "negation that keeps it: a copy that is on disk but untracked passes locally and fails for "
            + "everyone else.");
    }

    private static IEnumerable<FileInfo> Specifications() =>
        ArtifactFolders()
            .SelectMany(folder => folder.EnumerateFiles("*.json"))
            // The index is bookkeeping the generator owns — which fence an artifact
            // was authored from — not a specification anybody renders.
            .Where(file => !file.Name.Equals("index.json", StringComparison.OrdinalIgnoreCase));

    private static IEnumerable<FileInfo> Artifacts() =>
        ArtifactFolders().SelectMany(folder => folder.EnumerateFiles("*.html"));

    /// <summary>Every folder holding authored Archify specifications and the
    /// artifacts rendered from them.</summary>
    private static IEnumerable<DirectoryInfo> ArtifactFolders()
    {
        foreach (var knowledge in KnowledgeFolders)
        {
            var root = new DirectoryInfo(Path.Combine(RepositoryRoot.Root.FullName, knowledge));
            if (!root.Exists) continue;

            foreach (var folder in root.EnumerateDirectories(ArtifactFolder, SearchOption.AllDirectories))
            {
                yield return folder;
            }
        }

        var storybook = new DirectoryInfo(
            Path.Combine([RepositoryRoot.Root.FullName, .. StorybookFolder]));
        if (storybook.Exists) yield return storybook;
    }

    private static string Relative(FileSystemInfo file) =>
        Path.GetRelativePath(RepositoryRoot.Root.FullName, file.FullName).Replace('\\', '/');

    private static string Describe(string? animation) =>
        animation is null ? "nothing" : $"\"{animation}\"";
}
