using System.Globalization;

using Backlog.Infrastructure.Sqlite.Inbox;
using Backlog.Modules.Inbox.Abstractions;
using Backlog.Modules.Inbox.DomainModels;
using Backlog.Modules.Tasks.Abstractions;
using Backlog.Modules.Tasks.DomainModels;

using Microsoft.Data.Sqlite;

namespace Backlog.Infrastructure.Sqlite.UnitTests;

/// <summary>
/// The Inbox's three tables in the file the tasks already own. What these
/// assert is that an item put in comes back out unchanged — every column, and
/// the slug of a kind this build cannot read — and that sharing the file with
/// the task table costs neither side anything.
/// </summary>
public sealed class SqliteInboxRepositoryTests : IDisposable
{
    private static readonly DateTimeOffset Noon = new(2026, 9, 7, 12, 0, 0, TimeSpan.Zero);

    private readonly string _root;
    private readonly SqliteInboxRepository _repository;

    public SqliteInboxRepositoryTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "backlog-sqlite-inbox-tests", Guid.NewGuid().ToString("n"));
        _repository = new SqliteInboxRepository(_root);
    }

    [Fact]
    public async Task A_new_store_holds_nothing()
    {
        Assert.Empty(await _repository.ListAsync(TestContext.Current.CancellationToken));
        Assert.Empty(await _repository.ListListsAsync(TestContext.Current.CancellationToken));
        Assert.Empty(await _repository.ListGroupsAsync(TestContext.Current.CancellationToken));
        Assert.Equal(Path.Combine(_root, "backlog.db"), _repository.DatabasePath);
    }

    [Fact]
    public async Task A_saved_item_comes_back_whole()
    {
        var list = Guid.CreateVersion7();
        var taskIds = new[] { Guid.CreateVersion7(), Guid.CreateVersion7() };

        var item = InboxItem.FromCapture(
            Guid.CreateVersion7(),
            "Ship the thing",
            new InboxSource("email", "@bob"),
            "https://example.com/spec.pdf",
            ContentKind.Document,
            capturedAt: Noon,
            receivedAt: Noon.AddMinutes(5));
        item.SetTags([new InboxTag("deploy", AutoGenerated: false), new InboxTag("spec", AutoGenerated: true)]);
        item.SetRepoIds(["JSdotNet/Backlog", "JSdotNet/Other"]);
        item.MoveToList(list);
        item.RouteToBacklog(taskIds, ["JSdotNet/Backlog", "JSdotNet/Other"], Noon.AddHours(1));

        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);
        var loaded = await _repository.GetAsync(item.Id, TestContext.Current.CancellationToken);

        Assert.NotNull(loaded);
        Assert.Equal(item.Id, loaded.Id);
        Assert.Equal("Ship the thing", loaded.Title);
        Assert.Equal(string.Empty, loaded.BodyMd);
        Assert.Equal("https://example.com/spec.pdf", loaded.SourceUrl);
        Assert.Equal(Noon, loaded.CapturedAt);
        Assert.Equal(Noon.AddMinutes(5), loaded.ReceivedAt);
        Assert.Equal(InboxStatus.Triaged, loaded.Status);
        Assert.Null(loaded.DeferredUntil);
        Assert.Equal(ContentKind.Document, loaded.Kind);
        Assert.Equal("document", loaded.KindSlug);
        Assert.Equal("email", loaded.Source.Channel);
        Assert.Equal("@bob", loaded.Source.Person);
        Assert.Equal([new InboxTag("deploy", false), new InboxTag("spec", true)], loaded.Tags);
        Assert.Equal([false, true], loaded.Tags.Select(tag => tag.AutoGenerated));
        Assert.Equal(["JSdotNet/Backlog", "JSdotNet/Other"], loaded.RepoIds);
        Assert.Equal(list, loaded.ListId);
        Assert.NotNull(loaded.Routing);
        Assert.Equal(RoutingDomain.Tasks, loaded.Routing.Domain);
        Assert.Equal(["JSdotNet/Backlog", "JSdotNet/Other"], loaded.Routing.RepoIds);
        Assert.Equal(taskIds, loaded.Routing.TaskIds);
        Assert.Equal(Noon.AddHours(1), loaded.Routing.RoutedAt);
        Assert.True(loaded.ReplicaBacked);
        Assert.True(loaded.ReplicaAckPending);
        Assert.Equal(item.UpdatedAt, loaded.UpdatedAt);
    }

    [Fact]
    public async Task A_deferred_item_keeps_its_date()
    {
        var item = Manual("Later");
        item.Defer(new DateOnly(2026, 10, 1), Noon.AddHours(1));

        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);
        var loaded = await _repository.GetAsync(item.Id, TestContext.Current.CancellationToken);

        Assert.NotNull(loaded);
        Assert.Equal(InboxStatus.Deferred, loaded.Status);
        Assert.Equal(new DateOnly(2026, 10, 1), loaded.DeferredUntil);
        Assert.False(loaded.ReplicaBacked);
        Assert.False(loaded.ReplicaAckPending);
        Assert.Null(loaded.Routing);
        Assert.Null(loaded.ListId);
    }

    /// <summary>A kind slug this build has no member for is stored verbatim
    /// and comes back as its own word, parsed to Text beside it — the rule that
    /// keeps a capture from a newer client in the queue rather than breaking it.</summary>
    [Fact]
    public async Task An_unknown_kind_slug_survives_the_round_trip()
    {
        var item = Manual("Something new");
        item.SetKind(InboxEnumMap.ParseKind("hologram"), "hologram");

        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);
        var loaded = await _repository.GetAsync(item.Id, TestContext.Current.CancellationToken);

        Assert.NotNull(loaded);
        Assert.Equal(ContentKind.Text, loaded.Kind);
        Assert.Equal("hologram", loaded.KindSlug);
    }

    /// <summary>A row whose tags column holds what the aggregate would refuse
    /// today — a person, written before the check caught <c>#@bob</c> — still
    /// loads, tag and all. Rehydration is a load, not an edit, and one bad row
    /// must not make every row unreadable. Written with raw SQL because the
    /// repository cannot be made to write such a row any more.</summary>
    [Fact]
    public async Task A_row_whose_tags_the_aggregate_would_refuse_still_loads_with_the_tag_kept()
    {
        var item = Manual("Written by an older build");
        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);

        await using (var connection = await OpenAsync())
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = "UPDATE inbox_items SET tags = $tags WHERE id = $id;";
            command.Parameters.AddWithValue("$tags", """[{"Name":"@bob","Auto":false},{"Name":"deploy","Auto":true}]""");
            command.Parameters.AddWithValue("$id", item.Id.ToString());
            await command.ExecuteNonQueryAsync(TestContext.Current.CancellationToken);
        }

        var loaded = Assert.Single(await _repository.ListAsync(TestContext.Current.CancellationToken));

        Assert.Equal(["@bob", "deploy"], loaded.Tags.Select(tag => tag.Name));
        Assert.Equal([false, true], loaded.Tags.Select(tag => tag.AutoGenerated));
        Assert.Equal(item.UpdatedAt, loaded.UpdatedAt);
    }

    [Fact]
    public async Task Saving_twice_updates_the_one_row()
    {
        var item = Manual("Once");
        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);

        item.Archive(Noon.AddHours(1));
        await _repository.SaveAsync(item, TestContext.Current.CancellationToken);

        var only = Assert.Single(await _repository.ListAsync(TestContext.Current.CancellationToken));
        Assert.Equal(InboxStatus.Archived, only.Status);
    }

    [Fact]
    public async Task The_list_is_every_status_newest_capture_first()
    {
        var older = Manual("Older", capturedAt: Noon);
        var newer = Manual("Newer", capturedAt: Noon.AddHours(2));
        var archived = Manual("Archived", capturedAt: Noon.AddHours(1));
        archived.Archive(Noon.AddHours(3));

        await _repository.SaveAsync(older, TestContext.Current.CancellationToken);
        await _repository.SaveAsync(newer, TestContext.Current.CancellationToken);
        await _repository.SaveAsync(archived, TestContext.Current.CancellationToken);

        Assert.Equal(
            ["Newer", "Archived", "Older"],
            (await _repository.ListAsync(TestContext.Current.CancellationToken)).Select(item => item.Title));
    }

    [Fact]
    public async Task Only_flagged_items_are_pending_acknowledgement()
    {
        var pending = FromPhone("Archived on the desktop");
        pending.Archive(Noon.AddHours(1));
        var sent = FromPhone("Already acknowledged");
        sent.Archive(Noon.AddHours(1));
        sent.MarkReplicaAcknowledged();
        var untouched = FromPhone("Still waiting");
        var manual = Manual("Never synced");
        manual.Archive(Noon.AddHours(1));

        foreach (var item in new[] { pending, sent, untouched, manual })
        {
            await _repository.SaveAsync(item, TestContext.Current.CancellationToken);
        }

        var flagged = Assert.Single(await _repository.ListPendingReplicaAckAsync(TestContext.Current.CancellationToken));
        Assert.Equal(pending.Id, flagged.Id);
    }

    // --- Lists and groups ---------------------------------------------------

    [Fact]
    public async Task Lists_and_groups_round_trip_and_delete_outright()
    {
        var group = InboxGroup.Create("Projects", 1, Noon);
        var areas = InboxGroup.Create("Areas", 0, Noon);
        var inside = InboxList.Create("Backlog", group.Id, 0, Noon);
        var top = InboxList.Create("Resources", null, 0, Noon);

        await _repository.SaveGroupAsync(group, TestContext.Current.CancellationToken);
        await _repository.SaveGroupAsync(areas, TestContext.Current.CancellationToken);
        await _repository.SaveListAsync(inside, TestContext.Current.CancellationToken);
        await _repository.SaveListAsync(top, TestContext.Current.CancellationToken);

        var groups = await _repository.ListGroupsAsync(TestContext.Current.CancellationToken);
        Assert.Equal(["Areas", "Projects"], groups.Select(g => g.Name));
        Assert.Equal(Noon, groups[0].CreatedAt);

        var lists = await _repository.ListListsAsync(TestContext.Current.CancellationToken);
        Assert.Equal(["Backlog", "Resources"], lists.Select(l => l.Name));
        Assert.Equal(group.Id, lists.Single(l => l.Name == "Backlog").GroupId);
        Assert.Null(lists.Single(l => l.Name == "Resources").GroupId);

        inside.Rename("Renamed");
        inside.MoveToGroup(null);
        await _repository.SaveListAsync(inside, TestContext.Current.CancellationToken);

        var renamed = (await _repository.ListListsAsync(TestContext.Current.CancellationToken)).Single(l => l.Id == inside.Id);
        Assert.Equal("Renamed", renamed.Name);
        Assert.Null(renamed.GroupId);

        await _repository.DeleteListAsync(top.Id, TestContext.Current.CancellationToken);
        await _repository.DeleteGroupAsync(group.Id, TestContext.Current.CancellationToken);

        Assert.Single(await _repository.ListListsAsync(TestContext.Current.CancellationToken));
        Assert.Single(await _repository.ListGroupsAsync(TestContext.Current.CancellationToken));
        Assert.Equal(1, await RowCountAsync("inbox_lists"));
        Assert.Equal(1, await RowCountAsync("inbox_groups"));
    }

    // --- Sharing the file ---------------------------------------------------

    [Fact]
    public async Task The_inbox_tables_are_added_to_a_database_the_tasks_already_made()
    {
        // The upgrade path for everyone who already has a backlog.db: the tasks
        // table is there, the inbox tables are not, and this repository creates
        // its own on the way in rather than expecting them (local ADR 0003).
        var tasks = new SqliteTaskRepository(_root);
        var task = new TaskItem("Was here first", "Body.", EntryType.Task);
        await tasks.SaveAsync(task, TestContext.Current.CancellationToken);
        Assert.False(await TableExistsAsync("inbox_items"));

        await _repository.SaveAsync(Manual("Arrived later"), TestContext.Current.CancellationToken);

        Assert.True(await TableExistsAsync("inbox_items"));
        Assert.Equal("Arrived later", Assert.Single(await _repository.ListAsync(TestContext.Current.CancellationToken)).Title);
        Assert.Equal("Was here first", Assert.Single(await tasks.ListAsync(TestContext.Current.CancellationToken)).Title);
        Assert.Equal(_repository.DatabasePath, tasks.DatabasePath);
    }

    [Fact]
    public async Task The_task_table_is_added_to_a_database_the_inbox_already_made_and_neither_touches_the_other()
    {
        await _repository.SaveAsync(Manual("Inbox first"), TestContext.Current.CancellationToken);
        Assert.False(await TableExistsAsync("tasks"));

        var tasks = new SqliteTaskRepository(_root);
        await tasks.SaveAsync(new TaskItem("Task later", "Body.", EntryType.Task), TestContext.Current.CancellationToken);

        Assert.True(await TableExistsAsync("tasks"));
        Assert.Equal(1, await RowCountAsync("tasks"));
        Assert.Equal(1, await RowCountAsync("inbox_items"));
        Assert.Single(
            Directory.EnumerateFiles(_root, "*", SearchOption.AllDirectories),
            file => Path.GetFileName(file) == "backlog.db");
    }

    // --- Following the root -------------------------------------------------

    [Fact]
    public async Task Pointing_the_rooted_repository_at_another_folder_moves_to_that_inbox()
    {
        var second = Path.Combine(Path.GetTempPath(), "backlog-sqlite-inbox-tests", Guid.NewGuid().ToString("n"));
        var root = _root;
        var rooted = new RootedSqliteInboxRepository(() => root);

        var item = Manual("In the first folder");
        await rooted.SaveAsync(item, TestContext.Current.CancellationToken);
        await rooted.SaveListAsync(InboxList.Create("Resources", null, 0, Noon), TestContext.Current.CancellationToken);

        root = second;
        try
        {
            Assert.Empty(await rooted.ListAsync(TestContext.Current.CancellationToken));
            Assert.Empty(await rooted.ListListsAsync(TestContext.Current.CancellationToken));
            Assert.Equal(Path.Combine(second, "backlog.db"), rooted.DatabasePath);

            root = _root;

            Assert.NotNull(await rooted.GetAsync(item.Id, TestContext.Current.CancellationToken));
            Assert.Single(await rooted.ListListsAsync(TestContext.Current.CancellationToken));
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            if (Directory.Exists(second)) Directory.Delete(second, recursive: true);
        }
    }

    [Fact]
    public void The_rooted_repository_will_not_be_built_without_a_way_to_read_the_root()
    {
        Assert.Throws<ArgumentNullException>(() => new RootedSqliteInboxRepository(null!));
    }

    // --- Helpers ------------------------------------------------------------

    private static InboxItem Manual(string title, DateTimeOffset? capturedAt = null) =>
        InboxItem.Capture(
            title,
            new InboxSource(InboxEnumMap.ManualChannel, Person: null),
            sourceUrl: null,
            ContentKind.Text,
            capturedAt ?? Noon,
            receivedAt: capturedAt ?? Noon,
            replicaBacked: false);

    private static InboxItem FromPhone(string title) =>
        InboxItem.FromCapture(
            Guid.CreateVersion7(),
            title,
            new InboxSource("mobile", Person: null),
            sourceUrl: null,
            ContentKind.Text,
            capturedAt: Noon,
            receivedAt: Noon);

    private async Task<int> RowCountAsync(string table)
    {
        await using var connection = await OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"SELECT COUNT(*) FROM {table};";

        return Convert.ToInt32(await command.ExecuteScalarAsync(TestContext.Current.CancellationToken), CultureInfo.InvariantCulture);
    }

    private async Task<bool> TableExistsAsync(string name)
    {
        await using var connection = await OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = $name;";
        command.Parameters.AddWithValue("$name", name);

        return Convert.ToInt32(await command.ExecuteScalarAsync(TestContext.Current.CancellationToken), CultureInfo.InvariantCulture) > 0;
    }

    private async Task<SqliteConnection> OpenAsync()
    {
        var connection = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = _repository.DatabasePath,
            Mode = SqliteOpenMode.ReadWriteCreate
        }.ToString());

        await connection.OpenAsync(TestContext.Current.CancellationToken);
        return connection;
    }

    public void Dispose()
    {
        // The connection pool can still hold the file open the instant a test
        // ends, and a temp folder that will not delete is not a failure worth
        // failing a green suite over.
        SqliteConnection.ClearAllPools();

        if (!Directory.Exists(_root)) return;
        try { Directory.Delete(_root, recursive: true); } catch (IOException) { } catch (UnauthorizedAccessException) { }
    }
}
