using Backlog.Modules.Inbox.Abstractions.DataTransferObjects;
using Backlog.Modules.Inbox.DomainModels;

namespace Backlog.Modules.Inbox.Services;

/// <summary>
/// Turns the aggregates into the shapes callers are allowed to hold. One place,
/// so a field added to an item is a deliberate decision to publish it rather
/// than something that leaks out of whichever handler happened to be edited —
/// which is how the two sync flags stay unpublished.
/// </summary>
internal static class InboxMapper
{
    public static InboxItemDto ToDto(this InboxItem item) => new(
        item.Id,
        item.Title,
        item.BodyMd,
        item.SourceUrl,
        item.CapturedAt,
        item.ReceivedAt,
        item.Status,
        item.Kind,
        item.KindSlug,
        item.Source.Channel,
        item.Source.Person,
        [.. item.Tags.Select(tag => new InboxTagDto(tag.Name, tag.AutoGenerated))],
        [.. item.RepoIds],
        item.ListId,
        item.Routing is { } routing
            ? new InboxRoutingDto(routing.Domain, routing.RepoIds, routing.TaskIds, routing.RoutedAt)
            : null,
        item.DeferredUntil);

    public static InboxListDto ToDto(this InboxList list) => new(list.Id, list.Name, list.GroupId, list.Order);

    public static InboxGroupDto ToDto(this InboxGroup group) => new(group.Id, group.Name, group.Order);
}
