using Backlog.Modules.Inbox.Abstractions;
using Backlog.Modules.Inbox.DomainModels;
using Backlog.SharedKernel.Handlers;
using Backlog.SharedKernel.Results;

namespace Backlog.Modules.Inbox.Features.SetTags;

/// <summary>Replaces an item's tags with what the person picked. Bare names;
/// every tag written this way is theirs, so none is auto-generated.</summary>
public sealed record SetTagsCommand(Guid Id, IReadOnlyList<string> Tags);

public sealed class SetTagsCommandHandler(IInboxItemRepository items)
    : ICommandHandler<SetTagsCommand, Result>
{
    public async Task<Result> Handle(SetTagsCommand command, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(command);

        var item = await items.GetAsync(command.Id, cancellationToken).ConfigureAwait(false);
        if (item is null) return Result.Failure(InboxErrors.ItemNotFound);

        try
        {
            item.SetTags(command.Tags.Select(name => new InboxTag(name, AutoGenerated: false)));
        }
        catch (ArgumentException)
        {
            // The aggregate refuses a person among the tags; to the picker that
            // is a validation message, not a crash.
            return Result.Failure(InboxErrors.PersonIsNotATag);
        }

        await items.SaveAsync(item, cancellationToken).ConfigureAwait(false);

        return Result.Success();
    }
}
