namespace Backlog.Modules.Inbox.Abstractions.DataTransferObjects;

/// <summary>
/// An inbox item as anything outside the module sees it: what was captured and
/// what has been decided about it, not what it can do.
/// <para>
/// <paramref name="KindSlug"/> rides beside <paramref name="Kind"/> for the one
/// case where the two disagree: a slug this build has no member for parses to
/// <see cref="ContentKind.Text"/> and the pane shows the slug's own word instead
/// of "Text", so a capture from a newer client is labelled rather than mislabelled.
/// </para>
/// <para>
/// The two sync bookkeeping fields on the aggregate — whether the id is a replica
/// capture's and whether an acknowledgement is waiting to be pushed — are
/// deliberately absent. Neither is a fact about the capture; both are the outbox's
/// business, and the outbox has its own port.
/// </para>
/// </summary>
public sealed record InboxItemDto(
    Guid Id,
    string Title,
    string BodyMd,
    string? SourceUrl,
    DateTimeOffset CapturedAt,
    DateTimeOffset ReceivedAt,
    InboxStatus Status,
    ContentKind Kind,
    string KindSlug,
    string Channel,
    string? Person,
    IReadOnlyList<InboxTagDto> Tags,
    IReadOnlyList<string> RepoIds,
    Guid? ListId,
    InboxRoutingDto? Routing,
    DateOnly? DeferredUntil);

/// <summary>One tag on an item. <paramref name="Name"/> is bare — no <c>#</c> —
/// and <paramref name="AutoGenerated"/> says whether a person typed it or a
/// capture source suggested it.</summary>
public sealed record InboxTagDto(string Name, bool AutoGenerated);

/// <summary>Where a triaged item went. <paramref name="TaskIds"/> are the entries
/// the Tasks context created for it, one per repository in
/// <paramref name="RepoIds"/> — or exactly one when no repository was named.</summary>
public sealed record InboxRoutingDto(
    RoutingDomain Domain,
    IReadOnlyList<string> RepoIds,
    IReadOnlyList<Guid> TaskIds,
    DateTimeOffset RoutedAt);
