<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Backlog.Mobile.Web</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backlog.ServiceDefaults\Backlog.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Backlog.Mobile.UI\Backlog.Mobile.UI.csproj" />
  </ItemGroup>

</Project>
