using Backlog.Modules.Inbox.Abstractions;

namespace Backlog.Modules.Inbox.DomainModels;

/// <summary>
/// Where a capture came from: the channel it arrived through and, when the
/// channel knows, the person behind it. <paramref name="Person"/> keeps its
/// <c>@</c>, the same way a person tag is stored in Tasks — the sigil is what
/// says "a person" and stripping it would need putting back at every reader.
/// </summary>
public sealed record InboxSource(string Channel, string? Person);

/// <summary>
/// One tag on an item, stored bare (no <c>#</c>) and compared by name without
/// regard to case, so <c>Deploy</c> and <c>deploy</c> are one tag rather than
/// two chips. Equality deliberately ignores <see cref="AutoGenerated"/>: a tag
/// a person then typed by hand is the same tag, now theirs.
/// </summary>
public sealed record InboxTag(string Name, bool AutoGenerated)
{
    public bool Equals(InboxTag? other) =>
        other is not null && string.Equals(Name, other.Name, StringComparison.OrdinalIgnoreCase);

    public override int GetHashCode() => StringComparer.OrdinalIgnoreCase.GetHashCode(Name);
}

/// <summary>
/// Where a triaged item went. Written once, when the item routes, and never
/// edited: it is the record of a decision, not a live link. <paramref name="TaskIds"/>
/// name aggregates in another context that may since have been deleted there,
/// which is why they are ids and not references.
/// </summary>
public sealed record RoutingTarget(
    RoutingDomain Domain,
    IReadOnlyList<string> RepoIds,
    IReadOnlyList<Guid> TaskIds,
    DateTimeOffset RoutedAt);
